# Automatic generation of documentation will be copied and checked into the 
# gh-pages branch.
name: Documentation generation CI

on:
  push:
    paths:
      - '.github/workflows/generate_docs.yml'
      - 'docs/**'
    branches:
      - master
      - develop

jobs:
  build:
    name: Generate documentation
    runs-on: ubuntu-latest

    steps:
      # checkout branch
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: docs

      # Install dblatex
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dblatex dbtoepub xsltproc

      # generate the documentation files
      - name: Generate documentation
        run: |
          cd docs
          dblatex -s texstyle.sty mobilitydb-workshop.xml
          dbtoepub -o mobilitydb-workshop.epub mobilitydb-workshop.xml
          mkdir html
          xsltproc --stringparam html.stylesheet "docbook.css" --stringparam chunker.output.encoding "UTF-8" --xinclude -o html/index.html /usr/share/xml/docbook/stylesheet/docbook-xsl/html/chunk.xsl mobilitydb-workshop.xml
          cp -r images docbook.css html/
          cp docbook.css html/

      # store the documentation files
      - name: Upload output directory
        uses: actions/upload-artifact@v2
        with:
          name: doc-files
          path: |
            docs/index.md
            docs/mobilitydb-workshop.pdf
            docs/mobilitydb-workshop.epub
            docs/html/docbook.css
            docs/html/images/*
            docs/html/*.html
          retention-days: 1


  copy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    needs: build

    steps:
      # checkout the gh-pages branch
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      # download the doc files, most of which are generated above
      - name: Download output directory
        uses: actions/download-artifact@v2
        with:
          name: doc-files
          path: docs-temp

      # Rename the directory to master
      - name: Rename the directory to master
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          rm -rf master
          mv docs-temp master

      # Rename the directory to master
      - name: Rename the directory to develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          rm -rf develop
          mv docs-temp develop

      # add, commit and push to gh-pages
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update docs'
          branch: gh-pages
